webapp/search/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from webapp.search.forms import MusicSearchForm
from webapp.search.search_in_sc import search_sc

blueprint = Blueprint('search', __name__, url_prefix='/searching')


@blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = MusicSearchForm()
    if form.validate_on_submit():
        flash('Search requested for author: {}'.format(
           form.search.data))
        return redirect(url_for('search.search_result'))
    return render_template('search/search.html', title="Let's find smth", form=form)


@blueprint.route('/search_result', methods=['GET', 'POST'])
def search_result():
    list_of_songs = search_sc()
    return render_template('search/search_result.html', title="what do we have here",
                           list_of_songs=list_of_songs)

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user, login_required
from webapp.db import db
from webapp.user.models import Favorite, User
from werkzeug.urls import url_parse
from webapp.user.forms import LoginForm, RegistrationForm


blueprint = Blueprint('user', __name__)


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    user = current_user
    form = LoginForm()
    if not current_user.is_authenticated:
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user is None or not user.check_password(form.password.data):
                flash('Invalid username or password')
                return redirect(url_for('user.login'))
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('user.index'))
    return render_template('index.html', title='Wharf', form=form)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        flash('Welcome back!')
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('user.index')
        return redirect(next_page)
    return render_template('user/login.html', title='Sign In', form=form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.index'))


@blueprint.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first()
    songs = Favorite.query.filter_by(user_id=user.id).all()
    return render_template('user/profile.html', title='My profile', user=user,
                           songs=songs)


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Welcome to da Boat!')
        return redirect(url_for('user.index'))
    return render_template('user/register.html', title='Register', form=form)


@blueprint.route('/add_song', methods=['POST', 'GET'])
@login_required
def add_song():
    song = request.form['song']
    user = current_user
    song_in_db = Favorite.query.filter_by(song=song, user_id=user.id).first()
    if not song_in_db:
        new_song = Favorite(song=song, user_id=user.id)
        db.session.add(new_song)
        db.session.commit()
    flash('You are have added the song to you favorite')
    return redirect(url_for('user.index'))


@blueprint.route('/remove_song', methods=['POST'])
def remove_song():
    song = request.form['song']
    user = current_user
    title = Favorite.query.filter_by(song=song, user_id=user.id).first()
    db.session.delete(title)
    db.session.commit()
    flash('You are have removed the song from you favorite')
    return redirect(url_for('user.index'))

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1. shrink-to-fit=yes">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% if title %}
        <title>{{ title }} - da Pirate's Boat</title>
        {% else %}
        <title>Welcome to da Boat!</title>
        {% endif %}
    </head>
    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal">
                    <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                    <nav class="navbar navbar-light bg-light">
                                            <a class="navbar-brand" href="#">
                                              <img src="https://pp.userapi.com/c851536/v851536660/f28b1/AVYLGhEDhKA.jpg" width="30" height="30" alt="">
                                              <li class="breadcrumb-item"><a href="{{ url_for('user.index') }}">da Boat</a></li>
                                            </a>
                                    </nav>
                              
                             
                            </ol>
                    </nav>
            </h5>
            <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a class="p-2 text-dark" href="{{ url_for('user.index') }}">Wharf</a>
                            {% if current_user.is_anonymous %}
                            <a class="p-2 text-dark" href="{{ url_for('user.login') }}">Sign up</a>
                            {% else %}
                            <a class="p-2 text-dark" href="{{ url_for('user.logout') }}">Logout</a>
                            {% endif %}
                            {% if not current_user.is_anonymous %}
                            <a class="p-2 text-dark" href="{{ url_for('user.user', username=current_user.username) }}">My profile</a>
                            {% else %}
                            <a class="p-2 text-dark" href="{{ url_for('user.login') }}">My profile</a>
                            {% endif %}
                            <a class="p-2 text-dark" href="{{ url_for('search.search') }}">Search</a>
                        </li>        
                    </ol>
            </nav>
        </div>
        {% block search %} {% endblock %}
        {% block content %}{% endblock %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

webapp/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class='d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm'>
    <div class="row">
        <div class="col-md-12">
            {% if current_user.is_anonymous %}
            <h2>Hello, <a href="{{ url_for('user.register') }}">user!</a></h2>
            {% else %}
            <h2>Hello, {{ current_user.username }}!</h2>
            {% endif %}
            <hr/>                
                <div class="row justify-content-md-center">
                        <!-- <div class="col-5">
                            <h3>Daily in Bandcamp:</h3><hr/>
                                {% for music in bc_list %}
                                    <iframe allowtransparency="{{ music.allowtransparency }}" frameborder="{{ music.frameborder }}" height="{{ music.height }}}" src="{{ music.src }}" style="{{ music.style }}" width="{{ music.width }}"></iframe><hr/> 
                                {% endfor %}
                        </div> -->                        
                        <div class="col-5">
                            <h3>New in SoundCloud:</h3><hr/>
                                {% for info in popular_sc %}
                                <body>
                                <h4>{{ info.genre }}</h4>
                                <h4>Name: {{ info.title }}</h4>
                                    <iframe id="sc-widget" src="https://w.soundcloud.com/player/?url={{ info.music_url }}" width="100%" height="100" scrolling="no" frameborder="no"></iframe>
                                    <script src="https://w.soundcloud.com/player/api.js" type="text/javascript"></script>
                                        <script type="text/javascript">
                                            (function(){
                                                var widgetIframe = document.getElementById('sc-widget'),
                                            widget       = SC.Widget(widgetIframe);
                                            widget.bind(SC.Widget.Events.READY, function() {
                                            widget.bind(SC.Widget.Events.PLAY, function() {
                                            // get information about currently playing sound
                                            widget.getCurrentSound(function(currentSound) {
                                            console.log('sound ' + currentSound.get('') + 'began to play');
                                                });
                                            });
                                            // get current level of volume
                                            widget.getVolume(function(volume) {
                                            console.log('current volume value is ' + volume);
                                            });
                                            // set new volume level
                                            widget.setVolume(50);
                                            // get the value of the current position
                                            });
                                            }());
                                        </script>
                                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
                                        <script>
                                            $(document).ready(function(){
                                                $("button").click(function(){
                                                    //  $.ajax({
                                                    //      url: '/users/add_song',
                                                    //      song: '{{ info.url }}',
                                                    //      type: 'POST'
                                                    // });
                                                     $.post("/users/add_song",
                                                     {song: "{{ info.url }}"});
                                                });
                                            });
                                        </script>
                                        <button>Add to favorite</button>
                                        <hr/>
                                        {% endfor %}
                                </body>
                            </div> 
                        <div class="col">   
                        {% if current_user.is_anonymous %}
                            <h2>Sign In</h2><hr/>
                            <h3><form action="" method="post" novalidate>
                                {{ form.hidden_tag() }}
                                <div class="form-group">
                                    {{ form.username.label }}<br>
                                    {{ form.username(size=20) }}
                                    {% for error in form.username.errors %}
                                    <span style="color:red;">[{{ error }}]</span>
                                    {% endfor %}
                                </div>                    
                                <div class="form-group">
                                    {{ form.password.label }}<br>
                                    {{ form.password(size=20) }}
                                    {% for error in form.password.errors %}
                                    <span style="color:red;">[{{ error }}]</span>
                                    {% endfor %}
                                </div>
                                <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                                <p>{{ form.submit() }}</p>
                                <p> New User? <a href="{{ url_for('user.register') }}">Click to Register!</a></p>
                            </form>        
                        {% endif %}
                        </div> 
                        <div class="col" align="right">
                            <h3>New in Bandcamp:</h3><hr/>
                                {% for info in popular_bc %}
                                <h4>{{ info.genre }}</h4>
                                <img style="-webkit-user-select: none;" src="https://f4.bcbits.com/img/a{{ info.art }}_8.jpg"> 
                                <h4>{{ info.title }}</h4>
                                <audio controls>
                                    <source src="{{ info.music_url }}" type="audio/mp3">
                                </audio>    
                                {% endfor %}  
                                </div>                                                                                
                </div>
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<body class="text-center">
    <div class="container">
            <h1>Sign In</h1>
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }}
                <p>
                    {{ form.username.label }}<br>
                    {{ form.username(size=32) }}
                    {% for error in form.username.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.password.label }}<br>
                    {{ form.password(sixe=32) }}
                    {% for error in form.password.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                <p>{{ form.submit() }}</p>
                <p> New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
            </form>
        </form>
    </div>
</body>
{% endblock %}

webapp/templates/player.html
{% extends "base.html" %}

{% block content %}
<body>
    <div class="col-8">
    <iframe id="sc-widget" src="https://w.soundcloud.com/player/?url=https://api.soundcloud.com/tracks/540823470" width="100%" height="465" scrolling="no" frameborder="no"></iframe>
            <script src="https://w.soundcloud.com/player/api.js" type="text/javascript"></script>
            <script type="text/javascript">
            (function(){
                var widgetIframe = document.getElementById('sc-widget'),
                    widget       = SC.Widget(widgetIframe);

                widget.bind(SC.Widget.Events.READY, function() {
                widget.bind(SC.Widget.Events.PLAY, function() {
                    // get information about currently playing sound
                    widget.getCurrentSound(function(currentSound) {
                    console.log('sound ' + currentSound.get('') + 'began to play');
                    });
                });
                // get current level of volume
                widget.getVolume(function(volume) {
                    console.log('current volume value is ' + volume);
                });
                // set new volume level
                widget.setVolume(50);
                // get the value of the current position
                });

            }());
            </script>
    </div>
</body>
{% endblock %}

webapp/templates/sound.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ title }}</title>
  </head>
  <body>
    <div class='container'>
    <h4>{{ text }}</h4>
  
    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>